version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"          # package.json directory
    schedule:
      interval: "weekly"    # daily | weekly | monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"